/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PoliticaDeTrocasRouteImport } from './routes/politica-de-trocas'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CuidadosComOsProdutosRouteImport } from './routes/cuidados-com-os-produtos'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as BrindesCorporativosRouteImport } from './routes/brindes-corporativos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'

const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeTrocasRoute = PoliticaDeTrocasRouteImport.update({
  id: '/politica-de-trocas',
  path: '/politica-de-trocas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadosComOsProdutosRoute = CuidadosComOsProdutosRouteImport.update({
  id: '/cuidados-com-os-produtos',
  path: '/cuidados-com-os-produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const BrindesCorporativosRoute = BrindesCorporativosRouteImport.update({
  id: '/brindes-corporativos',
  path: '/brindes-corporativos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/brindes-corporativos': typeof BrindesCorporativosRoute
  '/carrinho': typeof CarrinhoRoute
  '/conta': typeof ContaRoute
  '/cuidados-com-os-produtos': typeof CuidadosComOsProdutosRoute
  '/login': typeof LoginRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/produtos': typeof ProdutosRoute
  '/sobre-nos': typeof SobreNosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brindes-corporativos': typeof BrindesCorporativosRoute
  '/carrinho': typeof CarrinhoRoute
  '/conta': typeof ContaRoute
  '/cuidados-com-os-produtos': typeof CuidadosComOsProdutosRoute
  '/login': typeof LoginRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/produtos': typeof ProdutosRoute
  '/sobre-nos': typeof SobreNosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/brindes-corporativos': typeof BrindesCorporativosRoute
  '/carrinho': typeof CarrinhoRoute
  '/conta': typeof ContaRoute
  '/cuidados-com-os-produtos': typeof CuidadosComOsProdutosRoute
  '/login': typeof LoginRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/produtos': typeof ProdutosRoute
  '/sobre-nos': typeof SobreNosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/brindes-corporativos'
    | '/carrinho'
    | '/conta'
    | '/cuidados-com-os-produtos'
    | '/login'
    | '/perguntas-frequentes'
    | '/politica-de-trocas'
    | '/produtos'
    | '/sobre-nos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/produto/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brindes-corporativos'
    | '/carrinho'
    | '/conta'
    | '/cuidados-com-os-produtos'
    | '/login'
    | '/perguntas-frequentes'
    | '/politica-de-trocas'
    | '/produtos'
    | '/sobre-nos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/produto/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/brindes-corporativos'
    | '/carrinho'
    | '/conta'
    | '/cuidados-com-os-produtos'
    | '/login'
    | '/perguntas-frequentes'
    | '/politica-de-trocas'
    | '/produtos'
    | '/sobre-nos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/produto/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrindesCorporativosRoute: typeof BrindesCorporativosRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ContaRoute: typeof ContaRoute
  CuidadosComOsProdutosRoute: typeof CuidadosComOsProdutosRoute
  LoginRoute: typeof LoginRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  PoliticaDeTrocasRoute: typeof PoliticaDeTrocasRoute
  ProdutosRoute: typeof ProdutosRoute
  SobreNosRoute: typeof SobreNosRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-trocas': {
      id: '/politica-de-trocas'
      path: '/politica-de-trocas'
      fullPath: '/politica-de-trocas'
      preLoaderRoute: typeof PoliticaDeTrocasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidados-com-os-produtos': {
      id: '/cuidados-com-os-produtos'
      path: '/cuidados-com-os-produtos'
      fullPath: '/cuidados-com-os-produtos'
      preLoaderRoute: typeof CuidadosComOsProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brindes-corporativos': {
      id: '/brindes-corporativos'
      path: '/brindes-corporativos'
      fullPath: '/brindes-corporativos'
      preLoaderRoute: typeof BrindesCorporativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BrindesCorporativosRoute: BrindesCorporativosRoute,
  CarrinhoRoute: CarrinhoRoute,
  ContaRoute: ContaRoute,
  CuidadosComOsProdutosRoute: CuidadosComOsProdutosRoute,
  LoginRoute: LoginRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  PoliticaDeTrocasRoute: PoliticaDeTrocasRoute,
  ProdutosRoute: ProdutosRoute,
  SobreNosRoute: SobreNosRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
